name: ${PROJECT_NAME}

services:
  nginx:
    image: '${NGINX_IMAGE}'
    container_name: ${PROJECT_NAME}-nginx
    ports:
      - '80:80'
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '${NGINX_CPU_LIMIT}'
          memory: ${NGINX_MEM_LIMIT}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - global-proxy-network
          
networks:
  global-proxy-network:
    name: global-proxy-network
